f=open('test.txt','w')
f.write('Pyton is a programming language\n')
f.write('This is a powerful language to handle data\n')
f.write('It has rich source of library\n')
f.write('It is a platform independent programming language\n')
f.write('It is used for web development')
f.close()
f=open('test.txt','r')
s=f.readlines()
print(s)
s=f.seek(0,0)
s=f.read(10)
print(s)
f.close()
